// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApw_WneyDTByuPSj0OuFAtIuY6vqci9LM',
    appId: '1:444610489913:web:6f3d406580a776a93be7e8',
    messagingSenderId: '444610489913',
    projectId: 'mhkcerp-1a913',
    authDomain: 'mhkcerp-1a913.firebaseapp.com',
    storageBucket: 'mhkcerp-1a913.firebasestorage.app',
    measurementId: 'G-N5W4SJVZKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEEzamxlQJXYfmaXdVw_zkt_9qxJZVwbg',
    appId: '1:444610489913:android:7c22cb3066c701cd3be7e8',
    messagingSenderId: '444610489913',
    projectId: 'mhkcerp-1a913',
    storageBucket: 'mhkcerp-1a913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGS1KCOOzKJb8HcTcrOuQIbVyc3CSbBI',
    appId: '1:444610489913:ios:33f4c0096686c68a3be7e8',
    messagingSenderId: '444610489913',
    projectId: 'mhkcerp-1a913',
    storageBucket: 'mhkcerp-1a913.firebasestorage.app',
    iosBundleId: 'com.example.regform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnGS1KCOOzKJb8HcTcrOuQIbVyc3CSbBI',
    appId: '1:444610489913:ios:33f4c0096686c68a3be7e8',
    messagingSenderId: '444610489913',
    projectId: 'mhkcerp-1a913',
    storageBucket: 'mhkcerp-1a913.firebasestorage.app',
    iosBundleId: 'com.example.regform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApw_WneyDTByuPSj0OuFAtIuY6vqci9LM',
    appId: '1:444610489913:web:9ad1f234a4e397db3be7e8',
    messagingSenderId: '444610489913',
    projectId: 'mhkcerp-1a913',
    authDomain: 'mhkcerp-1a913.firebaseapp.com',
    storageBucket: 'mhkcerp-1a913.firebasestorage.app',
    measurementId: 'G-6XMKCL00HL',
  );
}
